let clinicArticles=[];
let articleReturnFocus=null;
function clinicNewsImage(url){try{const value=new URL(url,location.href);return ['https:','http:'].includes(value.protocol)?value.href:'';}catch{return '';}}
const newsDialog=document.createElement('dialog');newsDialog.className='news-reader';newsDialog.setAttribute('aria-labelledby','newsArticleTitle');
newsDialog.innerHTML='<button type="button" class="news-reader-close" aria-label="關閉文章">×</button><article><p id="newsArticleDate"></p><h2 id="newsArticleTitle"></h2><img id="newsArticleImage" alt=""><div id="newsArticleBody"></div></article>';
document.body.append(newsDialog);
function openClinicArticle(item,trigger){articleReturnFocus=trigger||document.activeElement;newsDialog.querySelector('#newsArticleTitle').textContent=item.title;newsDialog.querySelector('#newsArticleDate').textContent=item.date||'';const image=newsDialog.querySelector('#newsArticleImage'),url=clinicNewsImage(item.image);image.hidden=!url;if(url){image.src=url;image.alt=item.title+'的文章圖片';}else image.removeAttribute('src');const body=newsDialog.querySelector('#newsArticleBody');body.replaceChildren();for(const paragraph of String(item.body||'').split(/\n\s*\n/)){const p=document.createElement('p');p.textContent=paragraph;body.append(p);}if(!newsDialog.open)newsDialog.showModal();newsDialog.scrollTop=0;document.body.style.overflow='hidden';newsDialog.querySelector('button').focus();}
newsDialog.querySelector('button').addEventListener('click',()=>newsDialog.close());newsDialog.addEventListener('click',event=>{const r=newsDialog.getBoundingClientRect();if(event.target===newsDialog&&(event.clientX<r.left||event.clientX>r.right||event.clientY<r.top||event.clientY>r.bottom))newsDialog.close();});newsDialog.addEventListener('close',()=>{document.body.style.overflow='';articleReturnFocus?.focus?.();});
function renderClinicNews(items){clinicArticles=items.filter(item=>item&&item.title);const section=document.getElementById('news'),container=document.getElementById('newsItems');container.replaceChildren();section.hidden=clinicArticles.length===0;
 for(const item of clinicArticles){const article=document.createElement('article');article.className='news-card';const imageUrl=clinicNewsImage(item.image);if(imageUrl){const image=document.createElement('img');image.src=imageUrl;image.alt=item.title+'的文章圖片';image.loading='lazy';const imageButton=document.createElement('button');imageButton.type='button';imageButton.className='news-image-open';imageButton.setAttribute('aria-label','放大圖片並閱讀：'+item.title);imageButton.append(image);imageButton.addEventListener('click',()=>openClinicArticle(item,imageButton));article.append(imageButton);}const text=document.createElement('div');text.className='news-card-content';if(item.date){const date=document.createElement('p');date.className='news-card-date';date.textContent=item.date;text.append(date);}const title=document.createElement('h3');const titleButton=document.createElement('button');titleButton.type='button';titleButton.className='news-title-open';titleButton.textContent=item.title;titleButton.addEventListener('click',()=>openClinicArticle(item,titleButton));title.append(titleButton);const excerpt=document.createElement('p');excerpt.className='news-excerpt';const plain=String(item.body||'').replace(/\s+/g,' ');excerpt.textContent=plain.length>100?plain.slice(0,100)+'…':plain;const open=document.createElement('button');open.type='button';open.textContent='閱讀全文 →';open.setAttribute('aria-label','閱讀全文：'+item.title);open.addEventListener('click',()=>openClinicArticle(item,open));text.append(title,excerpt,open);article.append(text);container.append(article);}
}
const articleStyle=document.createElement('style');articleStyle.textContent='#newsItems{grid-template-columns:repeat(3,minmax(0,1fr));align-items:stretch}#newsItems .news-card{padding:0;overflow:hidden;background:white;border:1px solid #e1ebe5;box-shadow:0 6px 22px #24453d0a;border-radius:16px;display:flex;flex-direction:column}.news-card .news-image-open{padding:0;margin:0;width:100%;align-self:stretch;display:block}.news-card .news-image-open img{width:100%;aspect-ratio:16/10;object-fit:cover;display:block}.news-card-content{padding:22px;display:flex;flex-direction:column;flex:1}.news-card-content h3{font-size:22px;line-height:1.5;margin:0 0 12px;color:#17674f;overflow-wrap:anywhere}.news-card-date{font-size:14px;color:#6b7d76;margin:0 0 8px}.news-excerpt{font-size:16px;line-height:1.8;overflow-wrap:anywhere;margin:0 0 18px}.news-card button{background:none;border:0;color:#17674f;font:inherit;font-weight:700;align-self:flex-start;padding:8px 0;margin-top:auto;cursor:pointer}.news-reader{border:0;border-radius:20px;padding:40px;width:min(780px,calc(100% - 32px));max-height:88vh;color:#24453d;box-shadow:0 20px 80px #12382e44;overflow:auto}.news-reader::backdrop{background:#183c32aa}.news-reader-close{position:sticky;top:0;float:right;border:0;border-radius:50%;background:#edf5ef;color:#24453d;width:40px;height:40px;font-size:26px;cursor:pointer}.news-reader h2{font-size:30px;line-height:1.5;margin:12px 44px 22px 0;overflow-wrap:anywhere}.news-reader article>img{display:block;width:100%;height:auto;border-radius:12px;margin-bottom:24px}.news-reader article>img[hidden]{display:none}#newsArticleDate{font-size:14px;color:#6b7d76}#newsArticleBody p{white-space:pre-line;line-height:1.95;font-size:17px;overflow-wrap:anywhere}.news-card .news-title-open{font:inherit;color:inherit;text-align:left;margin:0;padding:0}.news-card button:focus-visible,.news-reader-close:focus-visible{outline:3px solid #84bb9d;outline-offset:4px}@media(max-width:760px){#newsItems{grid-template-columns:repeat(2,minmax(0,1fr))}.news-reader{padding:22px}.news-reader h2{font-size:25px}}@media(max-width:480px){#newsItems{grid-template-columns:1fr}}';document.head.append(articleStyle);
